### ISSUE TITLE
controller logs aren't well formatted w/ ipld

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#100]
controller logs to stdout look like
```
 INFO    controller      log/log.go:35   retrieval task  {"uuid": {}, "miner": {}, "payload_cid": {}, "car_export": {}, "status": "", "duration (ms)": 2347}    
```

We should really serialize those in a better way

**Comment by mvdan** [comment]
My commit message from https://github.com/filecoin-project/dealbot/pull/109 was lost since we squash-merged, unfortunately. Closing manually.
