### ISSUE TITLE
timeout out taking longer than expected

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#110]
A retrieval that froze at 12:07 yesterday never seems to have timed out. 
It's still in "Stage": "FirstByteReceived" on the controller.  
Nothing got logged after that 12:07 "DealStatusOngoing" stage transition > 24hrs ago

**Comment by willscott** [comment]
may dup #28

**Comment by mgoelzer** [comment]
The 24 hour timeout should work irrespective of #28.  Regardless of reason for the hang, it should terminate after 24 hours of inactivity.

**Comment by willscott** [comment]
fixed with #147
