### ISSUE TITLE
export the public dag of finalized tasks as a car

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#116]
Add an endpoint on the controller in parallel to the libp2p based syncing

can use https://github.com/ipld/go-car/blob/9d4c555e62b616adbef38e6a1f7b55f40e3f4d4e/selectivecar.go#L64

**Comment by mvdan** [comment]
If/when we do this, it would be neat for the second integration test to verify this with the controller.

**Comment by willscott** [comment]
fixed in #122
