### ISSUE TITLE
Enable max retrieval payment per request

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/dealbot#123]
For Filecoin Discover, we'd like to use the deal bot to test for free retrieval. In order to do this properly, we'd need to be able to specify a max payment price for retrieval per request (alongside specifying miner and payload CID). 

Ideally this would allow us then to distinguish between an "out of funds" error on our Client and a miner attempting to charge non-agreed upon prices for our Client.

**Comment by jnthnvctr** [comment]
@ribasushi

**Comment by willscott** [comment]
it looks like we anticipated this for storage deals https://github.com/filecoin-project/dealbot/blob/main/tasks/gen.go#L97 but not retrieval deals beyond the payment price configured as default limits in the lotus the bot runs against

**Comment by mgoelzer** [comment]
Maybe a more general ability to set price per Gb.

Alternatively, use Lotus config for Discover deployment that sets max retrieval price at zero.  JV will see this show up as an error like "cannot agree on price."

**Comment by willscott** [comment]
this is fixed in #181
