### ISSUE TITLE
Provide journals in logging output (raul/f3 request)

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#127]
Every Lotus instance contains a set of json-formatted journal files.  These are sort of like an execution trace for that Lotus.  The journal json files are located in `$LOTUS_HOME/journal/`.  (If $LOTUS_HOME is not set, it defaults to `~/.lotus` for the user who started lotus, typically `ubuntu`.)

This issue is to track F3's request that these get pumped into wherever we are directing all the other logs to help them debug.  Not sure if the bot itself should do this or if we write a separate daemon that users inotify to decide when to ship the log out.

FYSI here's a sample line from a journal file:

```
{"System":"sync","Event":"head_change","Timestamp":"2021-04-07T20:15:51.881298228Z","Data":{"From":[{"/":"bafy2bzaceaz7ra62nv56uj3c4xscrvsfwc5hmfhequsvu3ob46jzrhhf5o7fi"},{"/":"bafy2bzaced46sac3pc4j4zqqo7hjkbzcacu2gje4qr7ja6537z6yidvrjhgrk"},{"/":"bafy2bzacebltiv6nuzfhivjj763ev5m4362vwqksoluog4e46bjbne7s67irs"}],"FromHeight":650020,"To":[{"/":"bafy2bzacebj3th5cesgalh6gs7272ervhtg5bjmgn6y7z4fpllsuepmt7y7fw"},{"/":"bafy2bzaceasknps4yfak3dzmsd4zuln7lor7qqe5f6v5zroqg2gwehmofx56k"},{"/":"bafy2bzaceauxjxsuuap26k575h3w2b5kmlno2chz733w7cfofvhjy2iw5iasq"},{"/":"bafy2bzacebtkogvidotfc3ns5k5jdk7ri4qbnnoih7pypxznirlil2dzwmyhq"},{"/":"bafy2bzacedmehtt5ezuvf5d7wrwv35j4bwmvtttpsjsvx2lakv7isuw6qpetq"}],"ToHeight":650602,"RevertCount":0,"ApplyCount":577}}
```

**Comment by willscott** [comment]
is there any way to get these through the API?

otherwise, this will be possible potentially through logz.io if the journal is being read to logs in the infra deployment, but otherwise is inaccessible to the dealbot since it'll live in the lotus container rather than the dealbot container.

**Comment by raulk** [comment]
If you're instantiating a lotus node programmatically, you can override the journal through DI with an alternate implementation that you control.

However, for our purposes, just shipping the journals to ES is enough. If the dealbot data contains the deal CID, that's enough to correlate.

**Comment by hannahhoward** [comment]
I am pretty sure we are not instantiating the node programmatically, but rather grabbing the api key from a normal lotus node running on the same machine and communicating of the normal Lotus JSON-RPC API.

That said -- the dealbot only contains the Payload CID (sometimes called Data CID) -- we may need to make a separate ticket to add tracking for the Deal CID (aka storage deal proposal CID right?)

**Comment by mgoelzer** [comment]
> If you're instantiating a lotus node programmatically, you can override the journal through DI with an alternate implementation that you control.

@raulk  Could we do this in Lotus instead?  Simplest implementation I can think of is an API call like `RegisterJournalListener` that lets the caller register a function that receives every message being written to the journal.  Dealbot would then use this hook to write the journal entries into logz.io or any other log aggregator.

This would allow the Dealbot project to just run vanilla lotus rather than patch the Lotus source to change the dependency injection.  Doesn't it feel like a better separation of concerns between Lotus and Dealbot?

**Comment by willscott** [comment]
I think the goal long term is to not need an API (this is internal debug info and not something a lotus client will regularly need permissions to get).
Rather, we expect that the lotus container k8s setup would be able to be run such that journal logs are piped to a log aggregator. That should be doable fully at the terraform level, and is an ask for infra, not an ask for lotus API.

**Comment by willscott** [comment]
@mgoelzer - is this needed to be surfaced in the dashbord? or is this for diagnostics and okay to be surfaced through log aggregator, as suggested in this issue?

**Comment by mgoelzer** [comment]
I think log aggregator only is fine, but let double check.

**Comment by mgoelzer** [comment]
Raul, has confirmed.  `surfaced through log aggregator` is what we want.

**Comment by willscott** [comment]
should i keep this here to track, or should we have it in the infra repo?
i think there may be a concern that these can get pretty big over time, but i think we just need to throw them through the log ingestion and hopefully we can set as relatively short expiry time on them

**Comment by mgoelzer** [comment]
They do get huge fast.

Yes, I think they should just go into logz.io.  If there’s nothing we need
to do in dealbot for that to happen, then I agree it should be in the infra
repo.

**Comment by coryschwartz** [comment]
As of a few days ago, these are being sent now to logz.io.  I think we can likely close this issue. @raulk maybe you can confirm this is usable.

**Comment by raulk** [comment]
Is this what's causing the data limits to be exceeded?

**Comment by dkkapur** [comment]
Pretty sure this is good to go, closing the tracking issue out. Can reopen as needed.
