### ISSUE TITLE
Status-specific Timeouts

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#134]
This is part of the timeouts plan here:  https://hackmd.io/w4qrkgdDR56joFisnn85pA?view#Status-specific-Timeouts

It hasn't been implemented yet.

I think we could probably set a 30- or 60-min max on StatusOngoing during a retrieval.  I don't think a round trip of the `payment -> transfer -> new payment` loop is every more than 1 Gb, but would need to double check.

**Comment by willscott** [comment]
fixed in #147
