### ISSUE TITLE
Dealbot not detecting task failures

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#154]
I have found that many of my controller's "in progress" tasks are actually fast fails on the Lotus CLI.  Moreover, they are stuck in Dealbot's `Status`==2 with the most recent `Log` being `[]`.  

This leads me to wonder if the Dealbot is unable to detect some types of failures, and therefore never gives up even though the task has failed.

This problem is common for me.  I have reproduced 4 examples of this behavior below.

### Example 1
Retrieval task for `bafykbzacecbckhdfm7tfu33d2nf3ayak3eabz5jqnbq6fvvmkwz26snywfbak` from `f023868`

When I try it on the CLI I get a <5 minute failure outcome with this output:

<details>
<pre>
$ lotus client retrieve --miner f023868  bafykbzacecbckhdfm7tfu33d2nf3ayak3eabz5jqnbq6fvvmkwz26snywfbak /dev/null
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 1.047 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 53.06 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 53.06 KiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentSent (DealStatusOngoing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventUnknownResponseReceived (DealStatusFailing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventCancelComplete (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: Unexpected deal response status: DealStatusErrored
</pre>
</details>

What `/tasks` endpoint shows for the same retrieval:
<details>
<pre>
        {
                "UUID": "fccf2845-bab0-4cdd-bdd4-20ab3d5118e8",
                "Status": 2,
                "WorkedBy": "6c259ba9",
                "Stage": "FirstByteReceived",
                "CurrentStageDetails": {
                        "Description": "First byte of data received from miner",
                        "ExpectedDuration": "a few seconds, or several hours when unsealing",
                        "Logs": []
                },
                "PastStageDetails": [
                        {
                                "Description": "Miner is online",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Tipset successfully fetched",
                                                "UpdatedAt": 1622051775472793116
                                        },
                                        {
                                                "Log": "Miner Info successfully fetched",
                                                "UpdatedAt": 1622051775504882089
                                        },
                                        {
                                                "Log": "Miner address validated",
                                                "UpdatedAt": 1622051775518991488
                                        },
                                        {
                                                "Log": "Connected to miner",
                                                "UpdatedAt": 1622051775623349552
                                        }
                                ],
                                "UpdatedAt": 1622051775623349552
                        },
                        {
                                "Description": "Miner responds to query ask",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Miner Offer Received",
                                                "UpdatedAt": 1622051775674739455
                                        }
                                ],
                                "UpdatedAt": 1622051775674739455
                        },
                        {
                                "Description": "Send proposal to miner",
                                "ExpectedDuration": "",
                                "Logs": [
                                        {
                                                "Log": "deal sent to miner",
                                                "UpdatedAt": 1622051775687565263
                                        }
                                ],
                                "UpdatedAt": 1622051775687565263
                        },
                        {
                                "Description": "Miner accepts deal",
                                "ExpectedDuration": "a few seconds",
                                "Logs": []
                        }
                ],
                "StartedAt": 1622051751501184822,
                "RunCount": 1,
                "RetrievalTask": {
                        "Miner": "f023868",
                        "PayloadCID": "bafykbzacecbckhdfm7tfu33d2nf3ayak3eabz5jqnbq6fvvmkwz26snywfbak",
                        "CARExport": false
                }
        },
</pre>
</details>

Miner seems to wait forever in `Status==2`.

### Example 2
Trying to retrieve `bafykbzacedxsme5frpjpvta3ah3w7vqmbz6nfgrplrgtl2mt5tf43zguxk6fe` from `f023861`

Fast failure on CLI:

<details>
<pre>
$ lotus client retrieve --miner f023861 bafykbzacedxsme5frpjpvta3ah3w7vqmbz6nfgrplrgtl2mt5tf43zguxk6fe /dev/null
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 960 B, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 52.95 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 52.95 KiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentSent (DealStatusOngoing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventUnknownResponseReceived (DealStatusFailing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventCancelComplete (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: Unexpected deal response status: DealStatusErrored
</pre>
</details>

What `/tasks` endpoint shows:

<details>
<pre>
        {
                "UUID": "68a0bc14-9dec-4332-bedd-aa9732b62c65",
                "Status": 2,
                "WorkedBy": "6c259ba9",
                "Stage": "FirstByteReceived",
                "CurrentStageDetails": {
                        "Description": "First byte of data received from miner",
                        "ExpectedDuration": "a few seconds, or several hours when unsealing",
                        "Logs": []
                },
                "PastStageDetails": [
                        {
                                "Description": "Miner is online",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Tipset successfully fetched",
                                                "UpdatedAt": 1622051776387958001
                                        },
                                        {
                                                "Log": "Miner Info successfully fetched",
                                                "UpdatedAt": 1622051776402519702
                                        },
                                        {
                                                "Log": "Miner address validated",
                                                "UpdatedAt": 1622051776422614097
                                        },
                                        {
                                                "Log": "Connected to miner",
                                                "UpdatedAt": 1622051776527582838
                                        }
                                ],
                                "UpdatedAt": 1622051776527582838
                        },
                        {
                                "Description": "Miner responds to query ask",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Miner Offer Received",
                                                "UpdatedAt": 1622051776590381478
                                        }
                                ],
                                "UpdatedAt": 1622051776590381478
                        },
                        {
                                "Description": "Send proposal to miner",
                                "ExpectedDuration": "",
                                "Logs": [
                                        {
                                                "Log": "deal sent to miner",
                                                "UpdatedAt": 1622051776604799120
                                        }
                                ],
                                "UpdatedAt": 1622051776604799120
                        },
                        {
                                "Description": "Miner accepts deal",
                                "ExpectedDuration": "a few seconds",
                                "Logs": []
                        }
                ],
                "StartedAt": 1622051776368890336,
                "RunCount": 1,
                "RetrievalTask": {
                        "Miner": "f023861",
                        "PayloadCID": "bafykbzacedxsme5frpjpvta3ah3w7vqmbz6nfgrplrgtl2mt5tf43zguxk6fe",
                        "CARExport": false
                }
        },
</pre>
</details>

### Example 3
Trying to retrieve `bafykbzacebpmipdxeb7ylfophje7n3brzr7ziu7aln2qkdliendgrxwp7fl3c` from `f023871`

Fast fail on CLI:

<details>
<pre>
$ lotus client retrieve --miner f023871 bafykbzacebpmipdxeb7ylfophje7n3brzr7ziu7aln2qkdliendgrxwp7fl3c  /dev/null
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 962 B, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 52.95 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 52.95 KiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentSent (DealStatusOngoing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventUnknownResponseReceived (DealStatusFailing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventCancelComplete (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: Unexpected deal response status: DealStatusErrored
</pre>
</details>

What `/tasks` shows:

<details>
<pre>
        {
                "UUID": "99b021b2-f434-40ba-8bfa-617294f35f1a",
                "Status": 2,
                "WorkedBy": "6c259ba9",
                "Stage": "FirstByteReceived",
                "CurrentStageDetails": {
                        "Description": "First byte of data received from miner",
                        "ExpectedDuration": "a few seconds, or several hours when unsealing",
                        "Logs": []
                },
                "PastStageDetails": [
                        {
                                "Description": "Miner is online",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Tipset successfully fetched",
                                                "UpdatedAt": 1622051776397905390
                                        },
                                        {
                                                "Log": "Miner Info successfully fetched",
                                                "UpdatedAt": 1622051776418129877
                                        },
                                        {
                                                "Log": "Miner address validated",
                                                "UpdatedAt": 1622051776442054420
                                        },
                                        {
                                                "Log": "Connected to miner",
                                                "UpdatedAt": 1622051776592889453
                                        }
                                ],
                                "UpdatedAt": 1622051776592889453
                        },
                        {
                                "Description": "Miner responds to query ask",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Miner Offer Received",
                                                "UpdatedAt": 1622051776642600090
                                        }
                                ],
                                "UpdatedAt": 1622051776642600090
                        },
                        {
                                "Description": "Send proposal to miner",
                                "ExpectedDuration": "",
                                "Logs": [
                                        {
                                                "Log": "deal sent to miner",
                                                "UpdatedAt": 1622051776654350950
                                        }
                                ],
                                "UpdatedAt": 1622051776654350950
                        },
                        {
                                "Description": "Miner accepts deal",
                                "ExpectedDuration": "a few seconds",
                                "Logs": []
                        }
                ],
                "StartedAt": 1622051776375730804,
                "RunCount": 1,
                "RetrievalTask": {
                        "Miner": "f023871",
                        "PayloadCID": "bafykbzacebpmipdxeb7ylfophje7n3brzr7ziu7aln2qkdliendgrxwp7fl3c",
                        "CARExport": false
                }
        },
</pre>
</details>

### Example 4
Trying to retrieve `bafykbzaceddea3nlgwfnn3npf62z3ny4vmlrrj23kdywfornxlwn65tel3liq` from `f024136`

Fast fail on CLI:

<details>
<pre>
$ lotus client retrieve --miner f024136 bafykbzaceddea3nlgwfnn3npf62z3ny4vmlrrj23kdywfornxlwn65tel3liq  /dev/null
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelCreateInitiated (DealStatusPaymentChannelCreating)
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusPaymentChannelAllocatingLane)
> Recv: 0 B, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)
> Recv: 1.049 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 53.06 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 53.06 KiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentSent (DealStatusOngoing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventUnknownResponseReceived (DealStatusFailing)
> Recv: 1.052 MiB, Paid 0.000000000002097152 FIL, ClientEventCancelComplete (DealStatusErrored)
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)
ERROR: retrieval failed: Retrieve: Retrieval Error: Unexpected deal response status: DealStatusErrored
</pre>
</details>

`/tasks` endpoint:

<details>
<pre>
        {
                "UUID": "873ec235-6425-4fab-b4af-3d691de80297",
                "Status": 2,
                "WorkedBy": "6c259ba9",
                "Stage": "FirstByteReceived",
                "CurrentStageDetails": {
                        "Description": "First byte of data received from miner",
                        "ExpectedDuration": "a few seconds, or several hours when unsealing",
                        "Logs": []
                },
                "PastStageDetails": [
                        {
                                "Description": "Miner is online",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Tipset successfully fetched",
                                                "UpdatedAt": 1622051776413038636
                                        },
                                        {
                                                "Log": "Miner Info successfully fetched",
                                                "UpdatedAt": 1622051776438431872
                                        },
                                        {
                                                "Log": "Miner address validated",
                                                "UpdatedAt": 1622051776466823138
                                        },
                                        {
                                                "Log": "Connected to miner",
                                                "UpdatedAt": 1622051776575160249
                                        }
                                ],
                                "UpdatedAt": 1622051776575160249
                        },
                        {
                                "Description": "Miner responds to query ask",
                                "ExpectedDuration": "a few seconds",
                                "Logs": [
                                        {
                                                "Log": "Miner Offer Received",
                                                "UpdatedAt": 1622051776609506130
                                        }
                                ],
                                "UpdatedAt": 1622051776609506130
                        },
                        {
                                "Description": "Send proposal to miner",
                                "ExpectedDuration": "",
                                "Logs": [
                                        {
                                                "Log": "deal sent to miner",
                                                "UpdatedAt": 1622051776634306872
                                        }
                                ],
                                "UpdatedAt": 1622051776634306872
                        },
                        {
                                "Description": "Miner accepts deal",
                                "ExpectedDuration": "a few seconds",
                                "Logs": []
                        }
                ],
                "StartedAt": 1622051776386849567,
                "RunCount": 1,
                "RetrievalTask": {
                        "Miner": "f024136",
                        "PayloadCID": "bafykbzaceddea3nlgwfnn3npf62z3ny4vmlrrj23kdywfornxlwn65tel3liq",
                        "CARExport": false
                }
        },
</pre>
</details>

**Comment by willscott** [comment]
should be fixed when bot is running with timeouts set from #147
