### ISSUE TITLE
When a retrieval hangs forever, we need to `lotus client cancel-retrieval` before retry

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#156]
This issue is a breakout of the [comment here](https://github.com/filecoin-project/dealbot/issues/141#issuecomment-848728382).  

The basic problem is that some retrievals will hang forever, and we need the dealbot both to timeout and then actually cancel the deal (API equivalent of `lotus client cancel-retrieve --deal-id 1600000000000000000`) before it retries.  Otherwise, all subsequent retries will fail because the original retrieval is still running as far as lotus is concerned.

**Comment by willscott** [comment]
this is blocked on dealid not being exposed by lotus.
Needs https://github.com/filecoin-project/lotus/issues/6415 resolved to be able to do this.
