### ISSUE TITLE
Pre-finalization script hook

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#172]
We have a use case for both Slingshot and Discover where we need to run a script after a retrieval is completed but before the task is finalized.  (The purpose of this is to do an `ipfs pin add` command on the newly retrieved script.)  The script would be run by an engine instance:  

 - on stdin the script would get basic parameters like the CID and miner ID
 - the script would return an exit code of 0 (success) or non-zero for error
 - for non-zero return values, the task would be finalized as a client error with the last line of the script's stdout going into `ErrorMessage` field on the finalized task

Maybe there is a better way to generalize this so it can apply to many different use cases, including ones we have no thought of yet.

**Comment by willscott** [comment]
confirming you want this on the daemon / engine process and not on the centralized controller process

**Comment by mgoelzer** [comment]
@willscott Yes, daemon.  It's unfortunate, but the use case of `ipfs pin add` has to be run on the engine box since that's where the go-ipfs daemons are running.
