### ISSUE TITLE
Track deal size

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#176]
Can we add logic to report the deal size both for storage deals and (successful) retrievals?  We want this shown on both the tasks endpoint and as a field available on the graphql endpoint.

**Comment by willscott** [comment]
we should be able to call [ClientListDeals](https://github.com/filecoin-project/lotus/blob/v1.9.0/api/proxy_gen.go#L1310)

that should give us deal info's which contain the size:
https://github.com/filecoin-project/lotus/blob/ada7f97ba86a13b3fbe497021c9f3c939c617285/api/api_full.go#L702

**Comment by willscott** [comment]
@hannahhoward  you were expressing problems on the retrieval flow. do you happen to know if this approach will work for both storage and retrievals?

**Comment by willscott** [comment]
@mgoelzer will it be okay to just track the number of bytes transferred as a proxy for 'size of retrieval deal'?

**Comment by mgoelzer** [comment]
@willscott Yes, I think that's fine.
