### ISSUE TITLE
Check FIL and Datacap balance before accepting new task

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#179]
When the FIL or datacap balance falls below a certain threshold, a dealbot should stop accepting new tasks until a new default wallet is installed with a refreshed FIL and datacap balance.

The threshold should be `(parallelism integer) * 32 GiB` since most deals we do will be 32 GiB.

There is a [companion infra issue](https://github.com/filecoin-project/lotus-infra/issues/347) for refreshing the wallet.

**Comment by willscott** [comment]
added in #181 with cost calculation in #186
