### ISSUE TITLE
Show all stages, even those with 0 deals in that stage

### ISSUE THREAD

**Issue by pooja** [filecoin-project/dealbot#212]
The deal stage diagram currently only shows stages that have deals in them. However, this is difficult to conceptualize to understand how the overall picture looks, if you're not intimately familiar with all the stages of dealmaking and can fill in the missing stages yourself.

**Can we please show all stages (even those with 0 deals) so that the diagram stays stable even as the exact numbers in each state/transition change?**

<img width="695" alt="Screen Shot 2021-06-13 at 4 48 56 PM" src="https://user-images.githubusercontent.com/5668171/121825447-3fdbcf80-cc67-11eb-99e6-23881bc1ef16.png">

**Comment by dkkapur** [comment]
Current state diagram shows all steps. Closing this for now, can re-open for additional adjustments.
