### ISSUE TITLE
Change average time to first byte metric to "seconds" instead of milliseconds

### ISSUE THREAD

**Issue by pooja** [filecoin-project/dealbot#213]
The current dashboard shows "time to first byte" in milliseconds, instead of "seconds". However, the latency is currently large enough that the millisecond version of this metric is pretty hard to contextualize. Can we please show this metric in units of "seconds" with 3 decimal places so we can get to millisecond-level accuracy if needed?

<img width="614" alt="Screen Shot 2021-06-13 at 4 52 39 PM" src="https://user-images.githubusercontent.com/5668171/121825518-c42e5280-cc67-11eb-8247-b021d63bf93b.png">

**Comment by kylehuntsman** [comment]
Wrote up a quick fix for this. I forked the dashboard because I'm not quite sure how to persist or "commit" the change to the dashboard. You can view the new metric here: https://observablehq.com/d/237335658c536e9a.

**Comment by davidd8** [comment]
I'm seeing a high number for the TTFB. On the original dashboard it's "1596811.00 MS" which should translate to 26m, however the fix shows a 23 hours next to it as well.

**Comment by kylehuntsman** [comment]
Oh you know what? It's doing weird time math. It's showing 0 hours for me, but you're an hour behind me, which would be 1 less hour, wrapping around to 23. I'll have to do this another way.

**Comment by kylehuntsman** [comment]
Okay, a fix has been pushed. A UTC date is now being used to generate the units instead of a local time.

**Comment by davidd8** [comment]
LGTM
