### ISSUE TITLE
Parse json in logz.io

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#228]
@raulk recently pointed out that what shows up in logz.io is a long json string, rather than json parsed into fields.  This is a known issue.  Logging it here as a note that we should unpack the json string.

**Comment by willscott** [comment]
currently an env on the docker image that is run in infra triggers logging to json: https://github.com/filecoin-project/dealbot/blob/main/main.go#L87-L89

**Comment by willscott** [comment]
this might be relevant terraform: https://github.com/filecoin-project/lotus-infra/blob/master/kubernetes/mainnet-us-east-1-eks/helm/ntwk-mainnet-dealbot/filecoin/dealbot/base.yaml
