### ISSUE TITLE
on restart, dealbot should tell controller to reset all its deals to available

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/dealbot#229]
When a dealbot starts up, it should announce itself to the controller, and the controller should reset any tasks previously assigned to the dealbot to having not been run

**Comment by willscott** [comment]
I believe this obsolete by the scheduling refactor. there shouldn't be any assigned-but-not-run tasks any more (feel free to re-open or make a more specific issue if i'm mistaken)
