### ISSUE TITLE
Maximum price for unverified deals should be 0.00000002 FIL/GB/epoch

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/dealbot#237]
In some earlier documents, I said we could set the maximum price the bot will pay to `0.001` FIL for a deal.  But after doing the calculations, I realize that would make a 32 GiB deal worth millions of the dollars -- obviously more than is in our test wallets.

I think we should set the max price the bot will pay on a storage or retrieval deal to `0.00000002`.  This works out to able 1.2 FIL for a 32 GiB unverified deal.

**Comment by mgoelzer** [comment]
@willscott Wasn't sure who to ping on this.

**Comment by willscott** [comment]
so to confirm, this would be a `MaxPriceAttoFil` of `20000000000`?

**Comment by mgoelzer** [comment]
@willscott Yes, looks correct to me.  2e-8 FIL = 20000000000 (as you say)
