### ISSUE TITLE
Expose Deal Proposal CID through GraphQL endpoint

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dealbot#271]

**Comment by hannahhoward** [comment]
@raulk for retrievals, I assume you don't care about Proposal CID, but rather retrieval DealID -- that's what is tracked in the FSM for retrievals I think.

**Comment by hannahhoward** [comment]
Also do you need on chain deal ID for Storage or is ProposalCID sufficient?

**Comment by hannahhoward** [comment]
@willscott 's PR above attempts to get more data but doesn't actually work. I want to confirm the minimum viable set of things you need, which based on my existing knowledge of markets software is ProposalCID for Storage Deals and Retrieval DealID for retrieval deals (which based on my knowledge of markets software, unless it's changed, are how the FSMs are key'd)

**Comment by raulk** [comment]
Thanks for checking. Let's go with your call @hannahhoward. For storage deals I think the ProposalCID would be enough as that's what enables us to correlate with the journal, but the DealID would be good to have, as you noted. For retrievals, I agree with you.

**Comment by willscott** [comment]
these are now available
