### ISSUE TITLE
Outcome misclassification on two storage deals

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dealbot#272]
The following UUIDs are deals that concluded prematurely in the `StorageDealProposalAccepted` stage, and were marked as succeeding by the dealbot. Please analyse:

- 78d87834-5371-4dfd-91b1-d4dfcf8872f4
- c41c4751-a6f2-4d48-aa39-c03d4f95a41a

![image](https://user-images.githubusercontent.com/1101242/124398424-8fb13200-dd0d-11eb-8925-8a7a91644db2.png)

**Comment by hannahhoward** [comment]
My analysis is as follows:

- whether or not a deal is marked as "success" or "failed" is based on whether [strorageDealExecutor.executeAndMonitorDeal](https://github.com/filecoin-project/dealbot/blob/main/tasks/storage_deal.go#L259) returns an error
- there are two code paths by which we could return no error from this function
   - the first is when we hit StorageDealActive (https://github.com/filecoin-project/dealbot/blob/main/tasks/storage_deal.go#L390)
   - the second is when the deal update channel from ClientGetDealUpdates closes (https://github.com/filecoin-project/dealbot/blob/main/tasks/storage_deal.go#L346)
   
I am assuming something happened here that caused the second code path to get triggered. I think if the channel with Lotus closes for some reason we probably should mark the deal failed). However, I'd like to at least have a hypothesis as to why that channel could close -- network error? Lotus shutting down? I'm not sure. Either way I think we need to make 346 return an error? I think?

**Comment by willscott** [comment]
we fixed the bug behind these. closing this issue
