### ISSUE TITLE
resume monitoring of ongoing deals on restart, instead of declaring them as errored

### ISSUE THREAD

**Issue by raulk** [filecoin-project/dealbot#286]
A bunch of new storage deals are in the errored state due to "Client error: Update channel closed before deal is active state".

I’ve checked what business logic on Lotus side can lead to the channel returned from [ClientGetDealUpdates](https://github.com/filecoin-project/lotus/blob/3f3336340f45b1ff5eb7c36333fd8bdd886fcab8/node/impl/client/client.go#L360) to be closed too soon, and the answer seems to be: nothing.

Note that because JSON-RPC is being used here, the lifetime of this channel is actually managed by go-jsonrpc.

Situations I can think of where the go-jsonrpc would be closing the channel is on (1) client-side or (2) node-side shutdown (the client being dealbot’s JSON-RPC client, and the node being the Lotus full node).

Can (1) be what’s happening here? An (orderly) shutdown of the dealbot controller closes the JSON-RPC client, and ends up recording these channel closures incorrectly as deal failures?

Storage deals take a while to land and fully be activated, so dealbot should be resuming the monitoring on a restart, instead of declaring these as errored.

![image](https://user-images.githubusercontent.com/1101242/125159681-c43f4680-e170-11eb-947c-51b9b22c23e1.png)

**Comment by hannahhoward** [comment]
Resuming monitoring on restart is not a small thing to implement and it's not generally the our intention to do so. There is a decent amount of design work to figure out how to do it correctly. I would refer this to @willscott to decide if it is worth prioritizing.

**Comment by willscott** [comment]
Our aim has been that redeploys will be rare enough in steady state that we can get away with saying that errors resulting from us tearing down a daemon or lotus in the middle of a deal can be ignored and should eventually constitute only a small fraction of overall deals.

If the lotus pod is restarted, the logic in the json-rpc lotus API will attempt to reconnect (it does have a fairly forgiving reconnect / retry logic before bubbling up the error from last time i looked into it) but there may well be cases where lotus becomes unavailable long enough that a batch of deals get marked as failed by the daemon. It seems as likely as not in these cases it's meant to be a re-deploy of a lotus pod with fresh state and we shouldn't a-priori expect in progress deals to transfer in those cases. it seems reasonable to throw them out and hope it's rare.

**Comment by raulk** [comment]
> Our aim has been that redeploys will be rare enough in steady state

This is a debatable assumption. I expect dealbot to be a significantly active project/deployment going forward, especially as its intended use cases are rolled out (we're still very early in its production usage). We should expect redeploys to be quite frequent.

---

@willscott I suspect what we're seeing here is the result of a [graceful dealbot shutdown](https://github.com/filecoin-project/dealbot/blob/0ea3584c41b103d14158410981818ea404774018/main.go#L23-L32). This leads to the JSON-RPC client being closed on the dealbot side, which to active goroutines consuming deal updates appears as an abrupt closure before the deal was complete.

An acceptable solution would be to introduce a new state that marks these deals as "incomplete" rather than "errored". Then we could filter those out from DSR statistics (it's also not fair for a miner to get penalised for a dealbot shutdown...) and we could avoid sinking time in analysing these.

**Comment by willscott** [comment]
we are filtering this error state out from the ones published to reputation services, I think @hannahhoward can also easily have them filtered out from DSR statistics

**Comment by hannahhoward** [comment]
Yes, I added them to DSR filtering on Friday.

**Comment by dkkapur** [comment]
Closing this for now, can re-open if restarting monitoring is needed in the future.
