### ISSUE TITLE
Lotus journals should be shipped to elasticsearch / logz.io

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#297]
This is already being tracked by infra and prioritized. Included the issue here for completeness and to account for any additional work that may need to be done by the dealbot team for E2E integration.

**Comment by coryschwartz** [comment]
Journal events are being processed by filebeat and being sent to the dealbot_data logz.io. I'm marking this as closed; If we need to update filters or tags, we can do so pretty easily.
