### ISSUE TITLE
Deal dashboard filter groups / "quick filters"

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#300]
Would be great to have radius groups of filters / combinations of filters for specific scenarios so that there's a comprehensive grouping of filters for the various stakeholders that will come to this dashboard. This should include "quick" filter groups for: 

- M1 release (MinerX miners on bleeding edge + v1.11.1-dev + current filters)
- M1 milestone for deal success (MinerX miners + lotus >= 1.11.0 + current filters)
- MinerX DSR (MinerX miners without any version or failure filters) 
- Network wide deal success (no filters)

**Comment by hannahhoward** [comment]
Per convo in colo, I think we decided we're just going to use the link sharing functionality for now to save filter presets. Can I close this @dkkapur ?

**Comment by dkkapur** [comment]
Yep - current plan of record is to use dedicated links for specific views / stakeholders
