### ISSUE TITLE
Support for 1GB, 2GB, and 4GB deal sizes

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#302]
Support for smaller (wider range of) deal sizes, which would be useful for testing:
- differing performance for different sizes
- differing success rates across sizes
- (DataCap will go further with more smaller deals)

Flag: this is not the highest priority because larger deal sizes are more extreme use cases and have a larger probability of being interrupted / failing.

**Comment by dkkapur** [comment]
Per conversation today - this is already supported in JSON, these options just need to be added to the dropdown on the  controller interface

**Comment by willscott** [comment]
done in #313
