### ISSUE TITLE
controller ingestion of tasks

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#31]
should have an endpoint (and maybe a simple form) for injecting an additional one-off task to the controller.

Probably needs to be authenticated. can be a fixed secret used for auth for now

**Comment by mvdan** [comment]
The endpoint is now done. Do we still want a web form?

I don't think we have any form of authentication right now.

**Comment by willscott** [comment]
i think we're probably fine w/o web form. I think we'll separate auth from the controller and expect it to be behind nginx basic auth or similar
