### ISSUE TITLE
Dealbot controller changes

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#311]
Went through the dealbot controller UI with @hannahhoward today and identified the following improvements that should be made:

"Tasks"
- P1: Expired tasks need to be cleaned up from the list of tasks

"Schedule Tasks"
- P1: Allow for a user to set deal sizes < 8GB (1, 2, 4). This is also captured here: https://github.com/filecoin-project/dealbot/issues/302
- P2: What time zone is the scheduling happening in? Can we get the time zone added to the view in the UI where the schedule is being set?

"Bots"
- P1: Show where in the spindown phase a dealbot is. Bot current state is not published so its difficult to know which "action" should happen for a bot when ready to spin down.
- P2: There is no way to know when a bot is actually ready to take on tasks. Adding some sort of status identified would help but is a low priority item / nice to have

"Create Bots"
- P1: Remove the workers field since this is configured in the dealbot code to be at 10 (though @hannahhoward is this an override option in which case we could consider keeping it? Did not feel like there was a real use case to ever request less than 10 though)
- P1: add max price filter for paid deals + retrievals in nanoFIL
- P1: lotus version for specific dealbot instance
- P1: Region should be a dropdown selector
- P2: Tags - we may want to consider doing a "here are existing tags you can use" option to ensure alignment with deployed bots

**Comment by willscott** [comment]
the only remaining part of this issue is:
"P1: Show where in the spindown phase a dealbot is. Bot current state is not published so its difficult to know which "action" should happen for a bot when ready to spin down."

I'm going to close this and open the more specific issue
