### ISSUE TITLE
lotus container not writing to EFS

### ISSUE THREAD

**Issue by coryschwartz** [filecoin-project/dealbot#318]
The lotus container was unable to write to the shared volume, resulting in deal failures. This happened after the storage backend was swapped to EFS in https://github.com/filecoin-project/lotus-infra/issues/394. 

The storage has gone through a few different iterations, so for context:
* Using a standard EBS (block storage) volume does not work, becasue it is a block volume, it cannot be mounted as writable in multiple locations.
* Using a volume local to the host, such as emptyDir or hostPath works fine. They are after all just a shared directory, but their use incurs the considerable downside that the volume size is limited to whatever is available on the host.

The move was made to use a pre-existing volume in this PR https://github.com/filecoin-project/helm-charts/pull/97 . This allows us to create a volume that permits multiple writers, an EFS volume (Amazon's NFS product)

The current bug is just simple unix permissions.
For security, the lotus container runs with as user `fc`. and this user lacks permission to write to the the root of the EFS volume, unfortunately.

I've already changed the permission, so lotus can now write to the volume, so this ticket is mostly for documentation, but I have some actions to follow up so this process is more automatic and doesn't require someone to `chmod` anything manually. I'll do the followup in separate infra ticket.

* Have dealbot write to a subdirectory of the volume rather than the root of the volume.
* Have an init container create the subdirectory and make sure the permissions on it are good.

**Comment by dkkapur** [comment]
Looks like this one is taken care of, thank you @coryschwartz! Please re-open if I misinterpreted the PR being closed.
