### ISSUE TITLE
Integrate a go-legs publisher endpoint to publish dealbot metadata

### ISSUE THREAD

**Issue by masih** [filecoin-project/dealbot#342]
The metadata in dealbot is already represented as DAG and exposed via graphQL [here](https://github.com/filecoin-project/dealbot/blob/main/controller/graphql/server.go#L178-L190). It would be useful to integrate a [go-legs publisher](https://github.com/filecoin-project/go-legs/blob/main/publish.go#L20) such that the same DAG is retrievable via a go-legs subscriber.

For example, this would be useful as the way to ingest dealbot metadata into a side chain reputation system.

- [x] Integrate go-legs into updates persisted by state db.
  - [x] Upgrade imld-prime.
  - [x] Upgrade Filecoin API.
- [x] Bootstrap go-legs libp2p host with Pando.
- [x] Configure runtime parameters and re-deploy dealbot.
- [x] Set up external IPs for libp2p host on dealbot controller and configure as listen addresses
- [x] Register dealbot as a provider in Pando
- [x] Confirm data is flowing on Pando side.
- [x] Publish Pando-compatible metadata

**Comment by dkkapur** [comment]
This represents the current plan to export dealbot data into pando

**Comment by masih** [comment]
Requires IPLD dependency upgrade first, being worked on in #343

**Comment by masih** [comment]
We now have dealbot libp2p exposed and serving legs sync requests. 

Dealbot is also registered as a provider on Pando side. The instance of dealbot registered is the one running on mainet production cluster.
