### ISSUE TITLE
Retrievals not working

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#353]
Likely due to lotus version upgrade causing changes to the retrieval RPC call, submitted retrievals via the endpoint are instantly failing with the following error:
```
"ErrorMessage": "RPC error (-32601): method 'Filecoin.ClientRetrieveWithEvents' not found",
```

We should fix this or revert back to an older lotus version per discussion in sync on Dec 3.

**Comment by willscott** [comment]
It looks like deployments currently re-deploy lotus with whatever's at https://hub.docker.com/r/coryschwartz/lotus/tags

Would be great if we can pin it to lotus v1.13.1 for now

**Comment by coryschwartz** [comment]
The image tag is set through the controller API when the bot is created

**Comment by willscott** [comment]
it looks like that is linked against
https://github.com/filecoin-project/helm-charts/blob/master/charts/lotus-bundle/values.yaml#L107

is there an easy way to pin lotus, rather than ending up with whatever is
in 'nightly'?

**Comment by willscott** [comment]
I see a place to specify lotus tag in dealbot, actually.

@Deep - we should try making a bot where that bottom field on the
controller is not the default 'nightly', but rather 'v1.13.1'

**Comment by dkkapur** [comment]
Just tried to deploy one, lets see if it works! Left everything the same, just added the tag `v1.13.1`.

**Comment by dkkapur** [comment]
@willscott - does this fix the RPC call issue or still requires additional wiring for retrievals to work? I have not been tracking the changes for v1.13

**Comment by willscott** [comment]
It should not cause "method 'Filecoin.ClientRetrieveWithEvents' not found" errors 🤞

**Comment by coryschwartz** [comment]
oh wow, @willscott I think that's actually a bug. We are deploying nightly regardless of what we supply throught he API. 


@dkkapur I made sure you're going to be running lotus v1.13.1 on that node, since that is clearly the intention. but it did deploy with `lotus:nightly` just now.

**Comment by dkkapur** [comment]
@coryschwartz thanks - can confirm that some of the retrievals I manually queued up today morning worked. 

Waiting for feedback from Slingshot side to see if bulk submissions via endpoint are going through fine as well.

**Comment by dkkapur** [comment]
Rollback worked. Slingshot deal submissions worked. Closing this out for now, tracking remaining items in linked issues.
