### ISSUE TITLE
Update retrieval RPC commands to work with lotus versions newer than v1.13.2

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#358]
Retrieval broke when we upgraded to v1.13.2. Not sure what the exact gap is but will likely need to upgrade soon again, so would be good to get the RPC commands updated to support retrieval. 

Currently a p2, but may escalate to p1. 

More context here: https://github.com/filecoin-project/dealbot/issues/353

**Comment by kuchaguangjie** [comment]
It might be fixed with newest commit, you may try again.

**Comment by davidd8** [comment]
This has most recently reoccurred and fixed as described in https://github.com/filecoin-project/dealbot/issues/377
