### ISSUE TITLE
dealbot drain - how to use it?

### ISSUE THREAD

**Issue by kuchaguangjie** [filecoin-project/dealbot#363]
I've started a dealbot controller with `--listen :8764`,
and started a dealbot daemon with `--id 1`,

Then call:
`dealbot drain -e http://127.0.0.1:8764 --id 1`

The first time it succeed, but the `daemon` is still running.

So I called it again, and get error:
```
2022-02-11T21:24:35.576+0800	INFO	controller	client/client.go:40	dealbot controller client initialized	{"addr": "http://127.0.0.1:8764"}
2022-02-11T21:24:35.577+0800	FATAL	dealbot	dealbot/main.go:94	Request failed: Bad Request
```

The controller also got error:
```
2022-02-11T21:24:35.577+0800	ERROR	controller	controller/tasks.go:104	drain worker DB error	{"err": "pq: duplicate key value violates unique constraint \"drained_workers_pkey\""}
```

Then I check table `drained_workers`, via sql:
> select * from drained_workers limit 5;

and found the value `1` exists, I guess that caused `duplicate key`.

---
**So, the questions are**:

- Should I specify the `--id` of daemon when start?
- If not, will the daemon get an id automatically? If so, how can I query those daemon ids?
- What does `drain` do? I saw it inserted 1 row _(containing the id)_ into table `drained_workers`, but the daemon process still running after that call.
---
Thanks.

**Comment by willscott** [comment]
> The first time it succeed, but the daemon is still running.

yes, the daemon will still be running.

drain will cause the controller to do the following:
1. stop providing any more tasks to the daemon
2. wait for the daemon to finish it's current tasks
3. mark the daemon's tasks as 'complete' - publishing them publicly.

Once the command returns / is complete the daemon can be safely stopped.

**Comment by kuchaguangjie** [comment]
@willscott Thanks, as my understanding:
1. The `drain`, stop further task, and publish current tasks; but don't actually stop daemon, need to stop the daemon afterwards by hand.
2. Once a `--id` of daemon is _drained_, the id can never be used again, since no task will be assign to it.

Not sure am I understanding correctly.
