### ISSUE TITLE
Retrievals are not working

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/dealbot#377]
All attempted retrievals from the API endpoint are failing. Dashboard displays: 
`RPC error (-32601): method 'Filecoin.ClientRetrieveWithEvents' not found`

Blocking all RSR attempts for Slingshot as well as general DSR reporting.

**Comment by dkkapur** [comment]
@timelytree can you share the response on the client side for the failing requests? AFAIK it is a `got error in offer: retrieval query offer was unavailable:` but would be good to get the latest input from you

**Comment by dkkapur** [comment]
cc @davidd8 @willscott

**Comment by willscott** [comment]
@hannahhoward any idea here. Has the v0 api been deprecated?

**Comment by willscott** [comment]
thanks to @hannahhoward for forward porting to current lotus https://github.com/filecoin-project/dealbot/releases/tag/v0.0.48 fixes this
