### ISSUE TITLE
Track deal status of active deal(s)

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#4]
The process should monitor events in status change of a deal it has initiated, and use the `inspect-deal` command to understand what has happened with them.

This may either need to be a regular poll on the API, or potentially there are events to allow us to react when deal status changes.

**Comment by mvdan** [comment]
I think we're already tracking for events that change the state of a storage deal: https://github.com/filecoin-project/dealbot/blob/401d1db62e5875533ad54096aa86343f7ceb1003/tasks/storage_deal.go#L118-L155

Is this what you mean here?

**Comment by willscott** [comment]
yep :)
