### ISSUE TITLE
support running the integration tests against an existing devnet

### ISSUE THREAD

**Issue by mvdan** [filecoin-project/dealbot#42]
For example, imagine running the tests against a continuously-running devnet on a remote machine, or against a local devnet kept running for a few hours for the sake of quickly running the tests without having to start and stop lotus every time.

**Comment by nonsense** [comment]
@mvdan we could certainly do that. Testground as a Service Kubernetes cluster (https://ci.testground.ipfs.team/tasks) is not heavily utilised, so we could totally have a long-running devnet there for example.

**Comment by mvdan** [comment]
That's also an option, but I think we could just support using the devnet running on @willscott's AWS machine for now - for example by mixing a simple script using `ssh` with `go test`.

**Comment by willscott** [comment]
this exists now, yeah?

**Comment by mvdan** [comment]
Yes :) header.sh now skips starting devnet if the right env var is set.
