### ISSUE TITLE
Latency to miner should be included in task

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#87]
I believe @hannahhoward has added a pre-task to the bot of checking connectivity and latency to the miner.
This value should be included in a structured way in the task record.

**Comment by mvdan** [comment]
We briefly looked into this in `tasks/storage_deal.go`, where dealbot talks to the miner, and there isn't an obvious place where the connection details to the miner (such as the latency/roundtrip) are exposed.

Will suggests to obtain the miner's multiaddress, and set up a libp2p host to connect to that address to get a latency measurement.

**Comment by willscott** [comment]
implemented in #191
