### ISSUE TITLE
Structure 'time to first byte' and 'time to last byte' in task record

### ISSUE THREAD

**Issue by willscott** [filecoin-project/dealbot#88]
when a task is successful, the stage details should be analyzed to pull out the time to first byte and time to last byte and record these as structured fields in the task record.

**Comment by willscott** [comment]
the structure is there now, but is not yet filled in.

**Comment by willscott** [comment]
@mvdan are we able to track the retrieval side of this now?

**Comment by mvdan** [comment]
It should be easy to do this now that Hannah improved the lotus stages and the integration tests work and include a retrieval with the daemon. I was going to continue on it tomorrow, but feel free to pick it up if it's urgent.
